#include "ctopp/model/network_model.hpp"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cstdint>
#include <unistd.h>
#include <net/if.h>        // if_nametoindex
#include <arpa/inet.h>     // ntohl for IP debug print

// ---------------------------------------------------------------------------
// PIMPL — hidden BPF state
// ---------------------------------------------------------------------------
namespace ctopp {
struct NetworkModel::Impl {
    void*       skel    = nullptr;  // struct traffic_monitor_bpf *
    void*       ringbuf = nullptr;  // struct ring_buffer *
    std::string bpf_obj_path;

    // TC attach state (for clean detach during stop)
    uint32_t ingress_handle   = 0;
    uint32_t ingress_priority = 0;
    bool     ingress_attached = false;
    uint32_t egress_handle    = 0;
    uint32_t egress_priority  = 0;
    bool     egress_attached  = false;
};
} // namespace ctopp

// ===========================================================================
// HAS_LIBBPF — full implementation
// ===========================================================================
#ifdef HAS_LIBBPF

#include "traffic_monitor.skel.h"   // generated by bpftool
#include <bpf/libbpf.h>

namespace ctopp {

// packet_meta must match the BPF-side definition in traffic_monitor.bpf.c.
// (bpftool gen skeleton does not export user-defined types.)
// NOTE: no #pragma pack — rely on natural alignment (implicit padding after
// protocol to keep length 4-aligned and timestamp_ns 8-aligned).
struct packet_meta {
    uint32_t src_ip;
    uint32_t dest_ip;
    uint16_t src_port;
    uint16_t dest_port;
    uint8_t  protocol;
    uint32_t length;
    uint64_t timestamp_ns;
};
// ---- C callback bridge ----
static int handle_event(void* ctx, void* data, size_t size) {
    auto* self = static_cast<NetworkModel*>(ctx);
    if (!self || !data || size < sizeof(packet_meta)) return 0;

    auto* meta = static_cast<const packet_meta*>(data);

    PacketRecord pkt{};
    pkt.src_ip       = meta->src_ip;
    pkt.dest_ip      = meta->dest_ip;
    pkt.src_port     = meta->src_port;
    pkt.dest_port    = meta->dest_port;
    pkt.protocol     = meta->protocol;
    pkt.length       = meta->length;
    pkt.timestamp_ns = meta->timestamp_ns;

    self->invoke_callback(pkt);
    return 0;
}

// ---- lifecycle ----
NetworkModel::NetworkModel() : impl_(std::make_unique<Impl>()) {}
NetworkModel::~NetworkModel() { stop(); }

void NetworkModel::invoke_callback(const PacketRecord& pkt) {
    if (callback_) callback_(pkt);
}

// ---- init ----
bool NetworkModel::init(const std::string& iface,
                        const std::string& bpf_obj_path) {
    iface_                = iface;
    impl_->bpf_obj_path   = bpf_obj_path;

    // 1. Open and load BPF skeleton
    auto* skel = traffic_monitor_bpf__open_and_load();
    if (!skel) {
        fprintf(stderr, "[NetworkModel] ERROR: open_and_load failed\n");
        return false;
    }
    impl_->skel = skel;
    fprintf(stderr, "[NetworkModel] BPF skeleton loaded (iface=%s)\n", iface_.c_str());

    // 2. Set up ring buffer consumer
    auto* rb = ring_buffer__new(bpf_map__fd(skel->maps.packet_events),
                                handle_event, this, nullptr);
    if (!rb) {
        fprintf(stderr, "[NetworkModel] ERROR: ring_buffer__new failed\n");
        traffic_monitor_bpf__destroy(skel);
        impl_->skel = nullptr;
        return false;
    }
    impl_->ringbuf = rb;
    fprintf(stderr, "[NetworkModel] ring buffer created\n");

    // 3. Attach TC filters via libbpf (shared maps with skeleton)
    {
        // Remove stale qdisc + filters from a previous run (idempotent).
        // This is necessary because a crashed/forgotten instance leaves the
        // BPF program attached with an exclusivity flag, blocking re-attach.
        char cmd[256];
        snprintf(cmd, sizeof(cmd),
                 "tc qdisc del dev %s clsact 2>/dev/null; "
                 "tc filter del dev %s ingress 2>/dev/null; "
                 "tc filter del dev %s egress 2>/dev/null",
                 iface_.c_str(), iface_.c_str(), iface_.c_str());
        system(cmd);
    }

    int ifindex = if_nametoindex(iface_.c_str());
    if (ifindex <= 0) {
        fprintf(stderr, "[NetworkModel] ERROR: invalid iface '%s'\n", iface_.c_str());
        ring_buffer__free(rb);           impl_->ringbuf = nullptr;
        traffic_monitor_bpf__destroy(skel); impl_->skel = nullptr;
        return false;
    }

    // Create clsact qdisc (idempotent — already exists on re-init)
    struct bpf_tc_hook tc_hook = {};
    tc_hook.sz          = sizeof(tc_hook);
    tc_hook.ifindex     = ifindex;
    tc_hook.attach_point = BPF_TC_INGRESS;
    (void)bpf_tc_hook_create(&tc_hook);

    // Attach ingress (uses skel's prog_fd → same maps as ring buffer)
    {
        struct bpf_tc_opts tc_opts = {};
        tc_opts.sz      = sizeof(tc_opts);
        tc_opts.prog_fd = bpf_program__fd(skel->progs.traffic_monitor);
        tc_hook.attach_point = BPF_TC_INGRESS;
        if (bpf_tc_attach(&tc_hook, &tc_opts)) {
            fprintf(stderr, "[NetworkModel] ERROR: tc ingress attach failed\n");
            ring_buffer__free(rb);           impl_->ringbuf = nullptr;
            traffic_monitor_bpf__destroy(skel); impl_->skel = nullptr;
            return false;
        }
        impl_->ingress_handle   = tc_opts.handle;
        impl_->ingress_priority = tc_opts.priority;
        impl_->ingress_attached = true;
        fprintf(stderr, "[NetworkModel] tc ingress attached\n");
    }

    // Attach egress
    {
        struct bpf_tc_opts tc_opts = {};
        tc_opts.sz      = sizeof(tc_opts);
        tc_opts.prog_fd = bpf_program__fd(skel->progs.traffic_monitor);
        tc_hook.attach_point = BPF_TC_EGRESS;
        if (bpf_tc_attach(&tc_hook, &tc_opts)) {
            fprintf(stderr, "[NetworkModel] ERROR: tc egress attach failed\n");
            // Roll back ingress
            tc_hook.attach_point = BPF_TC_INGRESS;
            struct bpf_tc_opts del_opts = {};
            del_opts.sz       = sizeof(del_opts);
            del_opts.handle   = impl_->ingress_handle;
            del_opts.priority = impl_->ingress_priority;
            bpf_tc_detach(&tc_hook, &del_opts);
            impl_->ingress_attached = false;
            ring_buffer__free(rb);           impl_->ringbuf = nullptr;
            traffic_monitor_bpf__destroy(skel); impl_->skel = nullptr;
            return false;
        }
        impl_->egress_handle   = tc_opts.handle;
        impl_->egress_priority = tc_opts.priority;
        impl_->egress_attached = true;
        fprintf(stderr, "[NetworkModel] tc egress attached\n");
    }

    return true;
}

// ---- start ----
void NetworkModel::start() {
    if (running_.exchange(true)) return;
    if (!impl_->skel || !impl_->ringbuf) {
        fprintf(stderr, "[NetworkModel] ERROR: start() before successful init()\n");
        running_ = false;
        return;
    }
    if (!callback_) {
        fprintf(stderr, "[NetworkModel] ERROR: start() without callback set\n");
        running_ = false;
        return;
    }
    worker_ = std::thread(&NetworkModel::poll_loop, this);
    fprintf(stderr, "[NetworkModel] poll thread started\n");
}

// ---- stop ----
void NetworkModel::stop() {
    if (!running_.exchange(false)) return;
    if (worker_.joinable()) worker_.join();
    fprintf(stderr, "[NetworkModel] poll thread stopped\n");

    // Detach TC filters + remove clsact qdisc
    {
        // Try libbpf detach first (cleaner)
        int ifindex = if_nametoindex(iface_.c_str());
        if (ifindex > 0) {
            struct bpf_tc_hook tc_hook = {};
            tc_hook.sz      = sizeof(tc_hook);
            tc_hook.ifindex = ifindex;

            if (impl_->ingress_attached) {
                struct bpf_tc_opts del_opts = {};
                del_opts.sz       = sizeof(del_opts);
                del_opts.handle   = impl_->ingress_handle;
                del_opts.priority = impl_->ingress_priority;
                tc_hook.attach_point = BPF_TC_INGRESS;
                bpf_tc_detach(&tc_hook, &del_opts);
                impl_->ingress_attached = false;
            }
            if (impl_->egress_attached) {
                struct bpf_tc_opts del_opts = {};
                del_opts.sz       = sizeof(del_opts);
                del_opts.handle   = impl_->egress_handle;
                del_opts.priority = impl_->egress_priority;
                tc_hook.attach_point = BPF_TC_EGRESS;
                bpf_tc_detach(&tc_hook, &del_opts);
                impl_->egress_attached = false;
            }
        }

        // Also nuke clsact from orbit — covers crashes where libbpf detach
        // above succeeded but the qdisc still holds stale state.
        char cmd[128];
        snprintf(cmd, sizeof(cmd), "tc qdisc del dev %s clsact 2>/dev/null",
                 iface_.c_str());
        system(cmd);
    }

    // Free ring buffer
    if (impl_->ringbuf) {
        ring_buffer__free(static_cast<struct ring_buffer*>(impl_->ringbuf));
        impl_->ringbuf = nullptr;
    }

    // Destroy skeleton
    if (impl_->skel) {
        traffic_monitor_bpf__destroy(
            static_cast<struct traffic_monitor_bpf*>(impl_->skel));
        impl_->skel = nullptr;
    }
    fprintf(stderr, "[NetworkModel] resources released\n");
}

// ---- poll_loop ----
void NetworkModel::poll_loop() {
    auto* rb = static_cast<struct ring_buffer*>(impl_->ringbuf);
    fprintf(stderr, "[NetworkModel] poll_loop started on iface=%s\n", iface_.c_str());

    while (running_.load()) {
        int err = ring_buffer__poll(rb, 100 /* ms */);
        if (err < 0 && err != -EINTR) {
            fprintf(stderr, "[NetworkModel] ring_buffer__poll error: %d\n", err);
            break;
        }
    }
    fprintf(stderr, "[NetworkModel] poll_loop exiting\n");
}

// ---- dropped_packets ----
uint64_t NetworkModel::dropped_packets() const {
    if (!impl_->skel) return 0;
    auto* skel = static_cast<traffic_monitor_bpf*>(impl_->skel);
    __u32 key = 0;
    __u64 val = 0;
    bpf_map__lookup_elem(skel->maps.drop_count, &key, sizeof(key),
                          &val, sizeof(val), 0);
    return val;
}

} // namespace ctopp

// ===========================================================================
// !HAS_LIBBPF — stub (compiles without libbpf)
// ===========================================================================
#else

namespace ctopp {

NetworkModel::NetworkModel() : impl_(std::make_unique<Impl>()) {}
NetworkModel::~NetworkModel() = default;

void NetworkModel::invoke_callback(const PacketRecord& pkt) {
    if (callback_) callback_(pkt);
}

bool NetworkModel::init(const std::string& iface,
                        const std::string& /*bpf_obj_path*/) {
    fprintf(stderr, "[NetworkModel] stub: libbpf unavailable (iface=%s)\n", iface.c_str());
    iface_ = iface;
    return true;
}

void NetworkModel::start()   { fprintf(stderr, "[NetworkModel] stub: start() ignored\n"); }
void NetworkModel::stop()    { fprintf(stderr, "[NetworkModel] stub: stop() ignored\n"); }

void NetworkModel::poll_loop() {
    fprintf(stderr, "[NetworkModel] stub: poll_loop not supported\n");
}

uint64_t NetworkModel::dropped_packets() const { return 0; }

} // namespace ctopp

#endif  // HAS_LIBBPF
